name: ishop
description: A very sexy Flutter template app!
version: 1.1.1+5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dynamic_theme: ^1.0.1
  eva_icons_flutter: ^2.0.1
  flare_flutter: ^2.0.6
  gradient_widgets: ^0.5.2
  liquid_swipe: ^1.5.0
  url_launcher: ^5.7.8
  google_maps_flutter: ^1.0.3
  http: ^0.12.2
  json_serializable: ^3.5.0
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  firebase_analytics: ^6.0.2
  google_sign_in: ^4.5.5
  geolocator: ^6.1.1
  flutter_polyline_points: ^0.2.4
  geocoding: ^1.0.5
  provider: ^4.3.2+2
  recase: ^3.0.0
  geoflutterfire: ^2.2.1
  device_info: ^0.4.2+9
  frino_icons: ^1.0.1+4
  rxdart: any
  google_maps_webservice: ^0.0.18
  collection: ^1.14.13
  supercharged: ^1.10.0
  font_awesome_flutter: ^8.10.0
  expandable: ^4.1.4
  tuple: ^1.0.3
  functional_widget_annotation: ^0.8.0
  logger: ^0.9.4
  get_it: ^5.0.1
  stacked: ^1.7.6
  auto_route: any
  stacked_services: any
  injectable: ^1.0.5
  get: ^3.15.0

dev_dependencies:
  analyzer: ^0.40.4
  flutter_launcher_icons: ^0.8.1
  pedantic: ^1.9.2
  build_runner: ^1.10.3
  functional_widget: any
  auto_route_generator: any
  injectable_generator: ^1.0.6

flutter_icons:
  android: 'launcher_icon'
  image_path_android: 'assets/icon/icon-legacy.png'
  adaptive_icon_foreground: 'assets/icon/icon-adaptive.png'
  adaptive_icon_background: '#fafafa'

  ios: true
  image_path_ios: 'assets/icon/icon-ios.png'

flutter:
  uses-material-design: true

  assets:
     - assets/credits/
     - assets/flare/
     - assets/icon/
     - assets/music/
     - assets/images/
     - assets/images.bak/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic
          weight: 400

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700

    - family: Metrophobic
      fonts:
        - asset: assets/fonts/Metrophobic/Metrophobic-Regular.ttf
          weight: 400

    - family: Spartan
      fonts:
        - asset: assets/fonts/Spartan/static/Spartan-Thin.ttf
          weight: 100
        - asset: assets/fonts/Spartan/static/Spartan-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Spartan/static/Spartan-Light.ttf
          weight: 300
        - asset: assets/fonts/Spartan/static/Spartan-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spartan/static/Spartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/Spartan/static/Spartan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Spartan/static/Spartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/Spartan/static/Spartan-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Spartan/static/Spartan-Black.ttf
          weight: 900

    - family: ConcertOne
      fonts:
        - asset: assets/fonts/ConcertOne/ConcertOne-Regular.ttf
          weight: 400

    - family: Neuton
      fonts:
        - asset: assets/fonts/Neuton/Neuton-Bold.ttf
          weight: 700
        - asset: assets/fonts/Neuton/Neuton-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Neuton/Neuton-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Neuton/Neuton-Light.ttf
          weight: 300
        - asset: assets/fonts/Neuton/Neuton-Regular.ttf
          weight: 400
        - asset: assets/fonts/Neuton/Neuton-Italic.ttf
          style: italic
          weight: 400
