name: ishop
description: iShop developemental app example
version: 1.1.1+5
publish_to: none

environment:
  sdk: ">=2.10.0-56.0.dev <2.12.0"

dependencies:
  charcode: ^1.2.0-nullsafety.3
  cloud_firestore: ^0.14.4
  collection: ^1.15.0-nullsafety
  firebase_analytics: ^6.3.0
  firebase_auth: ^0.18.4
  firebase_core: ^0.5.3
  flare_flutter: ^2.0.6
  flutter:
    sdk: flutter
  flutter_polyline_points: ^0.2.4
  font_awesome_flutter: ^8.10.0
  frino_icons: ^1.0.1+4
  geocoding: ^1.0.5
  geoflutterfire: ^2.2.1
  geolocator: ^6.1.10
  google_maps_flutter: ^1.0.6
  google_sign_in: ^4.5.6
  ishop_map_marker_info_window:
    path: packages/ishop_map_marker_info_window
  logger: ^0.9.4
  provider: ^4.3.2+3
  quiver: ^2.1.5
  recase: ^3.0.1
  rxdart: any
  source_span: ^1.8.0-nullsafety.4
  string_scanner: ^1.1.0-nullsafety.3
  supercharged: ^1.12.0
  tuple: ^1.0.3
  typed_data: ^1.3.0-nullsafety
  url_launcher: ^5.7.10


dev_dependencies:
  analyzer: 0.39.17
  auto_route_generator: any
  build: 1.3.0
  build_runner: 1.10.2
  flutter_launcher_icons: ^0.8.1

transitive_dependencies:
  google_maps_flutter_platform_interface: 1.0.5
  path: 1.8.0-nullsafety.3
  term_glyph: 1.2.0-nullsafety.3

transitive_dev_dependencies:
  _fe_analyzer_shared: 7.0.0
  build_config: 0.4.2
  build_runner_core: 6.0.1
  csslib: 0.16.2
  dart_style: 1.3.6
  file: 5.2.1
  html: 0.14.0+4
  json_annotation: 3.1.1
  node_interop: 1.2.1
  node_io: 1.2.0

flutter_icons:
  adaptive_icon_background: '#fafafa'
  adaptive_icon_foreground: 'assets/icon/icon-adaptive.png'
  android: 'launcher_icon'
  image_path_android: 'assets/icon/icon-legacy.png'

  ios: true
  image_path_ios: 'assets/icon/icon-ios.png'

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/logos/
     - assets/pins/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic
          weight: 400

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700

    - family: Metrophobic
      fonts:
        - asset: assets/fonts/Metrophobic/Metrophobic-Regular.ttf
          weight: 400

    - family: Spartan
      fonts:
        - asset: assets/fonts/Spartan/static/Spartan-Thin.ttf
          weight: 100
        - asset: assets/fonts/Spartan/static/Spartan-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Spartan/static/Spartan-Light.ttf
          weight: 300
        - asset: assets/fonts/Spartan/static/Spartan-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spartan/static/Spartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/Spartan/static/Spartan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Spartan/static/Spartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/Spartan/static/Spartan-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Spartan/static/Spartan-Black.ttf
          weight: 900

    - family: ConcertOne
      fonts:
        - asset: assets/fonts/ConcertOne/ConcertOne-Regular.ttf
          weight: 400

    - family: Neuton
      fonts:
        - asset: assets/fonts/Neuton/Neuton-Bold.ttf
          weight: 700
        - asset: assets/fonts/Neuton/Neuton-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Neuton/Neuton-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Neuton/Neuton-Light.ttf
          weight: 300
        - asset: assets/fonts/Neuton/Neuton-Regular.ttf
          weight: 400
        - asset: assets/fonts/Neuton/Neuton-Italic.ttf
          style: italic
          weight: 400
