include: all_lint_rules.yaml
# Enable all rules by default
analyzer:
  enable-experiment:
    - non-nullable
  errors:
    # Otherwise cause the import of all_lint_rules to warn because of some rules conflicts.
    # The conflicts are fixed in this file instead, so we can safely ignore the warning.
    included_file_warning: ignore
    # waiting on provider-nullsafety
    import_of_legacy_library_into_null_safe: ignore
    # not migrating external libs
    implementation_imports: ignore
  exclude:
    - "**/generated_plugin_registrant.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # incompatible with omit_local_variable_types
    always_specify_types: false
    # incompatible with prefer_single_quotes
    prefer_double_quotes: false
    # incompatible with prefer_final_locales
    unnecessary_final: false
    # prefer package imports
    prefer_relative_imports: false
    # waiting on provider-nullsafety
    import_of_legacy_library_into_null_safe: false
    # not migrating external libs
    implementation_imports: false
    # key goes first
    always_put_required_named_parameters_first: false
    # conflicts with turning off implicit dynamic
    avoid_annotating_with_dynamic: false
